# Model configuration and KD
model_name_or_path: /apdcephfs_qy3/share_301069248/users/rummyyang/minillm/checkpoints/llama3.2/Llama-3.2-1B


# Training methodology
stage: sft
do_train: true
finetuning_type: full

deepspeed: examples/deepspeed/ds_z2_config.json  # options: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

# Dataset configuration
dataset: BAAI-Infinity-Instruct-0625
template: llama3
cutoff_len: 2048
max_samples: 10000
overwrite_cache: false
preprocessing_num_workers: 16

# Output configuration
output_dir: saves/llama3-1b/full/sft
logging_steps: 10
save_steps: 100
plot_loss: false
overwrite_output_dir: true

# Training parameters
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 2.0e-05
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
